### ISSUE TITLE
Adicionar parâmetro para apenas pré-compilar

### ISSUE THREAD

**Issue by danielflira** [totvs/tds-ls#1]
Adicionar parâmetro para apenas pré-compilar e salvar os arquivos de resultados.

**Comment by ricardomansano** [comment]
Agradecemos a sugestão mas ela não faz parte da finalidade da ferramenta.

Você pode utilizar o plugin do TDS-VSCode para essa tarefa, indo nas configuração e solicitando que sejam mantidos os arquivos PPO.
