### ISSUE TITLE
Compilacao

### ISSUE THREAD

**Issue by danielAlbuquerque** [totvs/tds-ls#3]
To tentando compilar um fonte usando o advpls e to recebendo um erro(acredito que eu esteja esquecendo algo), segue os detalhes:

.INI
![image](https://user-images.githubusercontent.com/6063722/89111127-64043880-d428-11ea-8228-21f3e62a3d64.png)

Execucao:
![image](https://user-images.githubusercontent.com/6063722/89111137-7a11f900-d428-11ea-8021-55054de83385.png)

Appserver:
![image](https://user-images.githubusercontent.com/6063722/89111141-85652480-d428-11ea-97f6-548595d34caa.png)

**Comment by julioclisboa** [comment]
Daniel, boa noite.
Tente trocar as barras de \ para /

**Comment by brodao** [comment]
@danielAlbuquerque 

Seu server esta configurado para usar SLL. Ative a chave de conexão segura. No ini.
Detalhes https://github.com/totvs/tds-ls/blob/master/TDS-CLi.md
