### ISSUE TITLE
A action patchInfo não esta funcionando

### ISSUE THREAD

**Issue by Lucianopsantos** [totvs/tds-ls#6]
Prezados,

Estava testando o script do tds-ls pois antes usava o antigo tdscli. 
No tdscli o patchInfo funciona perfeitamente, mas não consegui fazer funcionar usando o advpls.exe.
Eu notei que essa funcionalidade na aba de aplicação da Patch também não funciona na extensão TOTVS VSCODE v1.3.2. 

-Segue o log:
c:\TOTVS\Bin>advpls --tdsCli=command.txt
[INFO] Starting validate server 127.1.1.1@11099
[INFO] Appserver detected with build version: 7.00.191205P and secure: 0
[INFO] Validate server 127.1.1.1@11099 finished
[INFO] Starting connection to the server 'tdscli.serverName' (127.1.1.1@11099)
[INFO] Connection to the server 'tdscli.serverName' finished.
[INFO] Starting user 'admin' authentication.
[INFO] Secure authenticating...
[INFO] User authenticated successfully.
[INFO] User 'admin' authentication finished.
[INFO] Starting patch info.
[INFO] Patch file: C:/GMUDS/12100113_mprimesp-24068_12_1_27_tttp120_lg.ptm
[INFO] Starting build for environment DEV01.
[INFO] Aborting end build (rollback changes).
[INFO] Patch info finished.
[INFO] Starting apply patch.
[INFO] Starting build for environment DEV01.
[INFO] Applying patch file: C:/GMUDS/12100113_mprimesp-24068_12_1_27_tttp120_lg.ptm
[INFO] Patch (12100113_mprimesp-24068_12_1_27_tttp120_lg.ptm) successfully applied.
[INFO] Committing end build.
[INFO] Apply patch finished.
[INFO] Starting RPO defragmentation.
[INFO] Starting build for environment DEV01.
[WARN] This process may take a while.
[INFO] RPO successfully defragged.
[INFO] Committing end build.
[INFO] RPO defragmentation finished.

-Arquivo command.txt:
[authentication]
action=authentication
server=127.1.1.1
port=11099
secure=0
build=AUTO
environment=DEV01
user=admin
psw=admin

[patchInfo]
action=patchInfo
patchFile=C:\GMUDS\12100113_mprimesp-24068_12_1_27_tttp120_lg.ptm
output=C:\GMUDS\tttp120.out
localPatch=True

[patchApply]
action=patchApply
patchFile=C:\GMUDS\12100113_mprimesp-24068_12_1_27_tttp120_lg.ptm
localPatch=True
applyOldProgram=False

[defragRPO]
action=defragRPO

-PachInfo no VsCode:
![Capturar](https://user-images.githubusercontent.com/59921276/127716511-ecfe0340-59d7-4e7f-a880-b9f1b1044dc7.PNG)

At.te.,

**Comment by danielbolognani** [comment]
Boa tarde, primeiramente desculpe a demora pela resposta, mas esse canal não é acompanhado pela nossa equipe pois trata-se de um repositório de apoio ao tds-VSCode.
Nossa equipe já vai acompanhar esse caso, mas por favor, no futuro pode abrir direto no https://github.com/totvs/tds-vscode/issues

**Comment by danielbolognani** [comment]
Obrigado por abrir o problema direto no repositório do tds-vscode, vamos acompanhar por lá então.
